spring.application.name=backend

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/KursyDB
spring.datasource.username=postgres
spring.datasource.password=slon

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mySecretKey123

spring.security.oauth2.client.registration.google.client-id=444814442874-caj8n0dk9t9catrjqugo4aceo13l5c72.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.frontend.oauth2-redirect-url=http://localhost:5173/

stripe.secret-key=sk_test_51TlFuS4hz7jYKd7f1ibJQIMqH769CHMaeZcc0fOq5yTJufyi5waE4q3mYKmLzShY6YNGhKkR9lycbZN0XHDEt4bt00GNi6ZcM8
stripe.success-url=http://localhost:5173/payment-success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel-url=http://localhost:5173/payment-cancel